// Mocks generated by Mockito 5.4.6 from annotations
// in dart_libp2p/test/protocol/circuitv2/buffered_reader_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i5;

import 'package:dart_libp2p/core/network/conn.dart' as _i2;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i4;
import 'package:dart_libp2p/core/network/stream.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConn_0 extends _i1.SmartFake implements _i2.Conn {
  _FakeConn_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeP2PStream_1<T1> extends _i1.SmartFake implements _i3.P2PStream<T1> {
  _FakeP2PStream_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamStats_2 extends _i1.SmartFake implements _i3.StreamStats {
  _FakeStreamStats_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamManagementScope_3 extends _i1.SmartFake
    implements _i4.StreamManagementScope {
  _FakeStreamManagementScope_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [P2PStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2PStream<T> extends _i1.Mock implements _i3.P2PStream<T> {
  MockP2PStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Conn get conn => (super.noSuchMethod(
        Invocation.getter(#conn),
        returnValue: _FakeConn_0(
          this,
          Invocation.getter(#conn),
        ),
      ) as _i2.Conn);

  @override
  _i3.P2PStream<_i5.Uint8List> get incoming => (super.noSuchMethod(
        Invocation.getter(#incoming),
        returnValue: _FakeP2PStream_1<_i5.Uint8List>(
          this,
          Invocation.getter(#incoming),
        ),
      ) as _i3.P2PStream<_i5.Uint8List>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get isWritable => (super.noSuchMethod(
        Invocation.getter(#isWritable),
        returnValue: false,
      ) as bool);

  @override
  String id() => (super.noSuchMethod(
        Invocation.method(
          #id,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #id,
            [],
          ),
        ),
      ) as String);

  @override
  String protocol() => (super.noSuchMethod(
        Invocation.method(
          #protocol,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #protocol,
            [],
          ),
        ),
      ) as String);

  @override
  _i7.Future<void> setProtocol(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setProtocol,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i3.StreamStats stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _FakeStreamStats_2(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        ),
      ) as _i3.StreamStats);

  @override
  _i4.StreamManagementScope scope() => (super.noSuchMethod(
        Invocation.method(
          #scope,
          [],
        ),
        returnValue: _FakeStreamManagementScope_3(
          this,
          Invocation.method(
            #scope,
            [],
          ),
        ),
      ) as _i4.StreamManagementScope);

  @override
  _i7.Future<_i5.Uint8List> read([int? maxLength]) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [maxLength],
        ),
        returnValue: _i7.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i7.Future<_i5.Uint8List>);

  @override
  _i7.Future<void> write(_i5.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> closeWrite() => (super.noSuchMethod(
        Invocation.method(
          #closeWrite,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> closeRead() => (super.noSuchMethod(
        Invocation.method(
          #closeRead,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setDeadline,
          [time],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setReadDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setReadDeadline,
          [time],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setWriteDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setWriteDeadline,
          [time],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
