// Mocks generated by Mockito 5.4.6 from annotations
// in dart_libp2p/test/protocol/circuitv2/relay_half_close_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:typed_data' as _i14;

import 'package:dart_libp2p/core/connmgr/conn_manager.dart' as _i7;
import 'package:dart_libp2p/core/crypto/keys.dart' as _i18;
import 'package:dart_libp2p/core/host/host.dart' as _i5;
import 'package:dart_libp2p/core/multiaddr.dart' as _i13;
import 'package:dart_libp2p/core/network/conn.dart' as _i2;
import 'package:dart_libp2p/core/network/context.dart' as _i19;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i4;
import 'package:dart_libp2p/core/network/stream.dart' as _i3;
import 'package:dart_libp2p/core/network/transport_conn.dart' as _i10;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i12;
import 'package:dart_libp2p/core/peerstore.dart' as _i9;
import 'package:dart_libp2p/p2p/protocol/circuitv2/client/client.dart' as _i17;
import 'package:dart_libp2p/p2p/transport/listener.dart' as _i11;
import 'package:dart_libp2p/p2p/transport/transport_config.dart' as _i8;
import 'package:dart_libp2p/p2p/transport/upgrader.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConn_0 extends _i1.SmartFake implements _i2.Conn {
  _FakeConn_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeP2PStream_1<T1> extends _i1.SmartFake implements _i3.P2PStream<T1> {
  _FakeP2PStream_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamStats_2 extends _i1.SmartFake implements _i3.StreamStats {
  _FakeStreamStats_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamManagementScope_3 extends _i1.SmartFake
    implements _i4.StreamManagementScope {
  _FakeStreamManagementScope_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHost_4 extends _i1.SmartFake implements _i5.Host {
  _FakeHost_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpgrader_5 extends _i1.SmartFake implements _i6.Upgrader {
  _FakeUpgrader_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnManager_6 extends _i1.SmartFake implements _i7.ConnManager {
  _FakeConnManager_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransportConfig_7 extends _i1.SmartFake
    implements _i8.TransportConfig {
  _FakeTransportConfig_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerstore_8 extends _i1.SmartFake implements _i9.Peerstore {
  _FakePeerstore_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransportConn_9 extends _i1.SmartFake implements _i10.TransportConn {
  _FakeTransportConn_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListener_10 extends _i1.SmartFake implements _i11.Listener {
  _FakeListener_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerId_11 extends _i1.SmartFake implements _i12.PeerId {
  _FakePeerId_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnState_12 extends _i1.SmartFake implements _i2.ConnState {
  _FakeConnState_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiAddr_13 extends _i1.SmartFake implements _i13.MultiAddr {
  _FakeMultiAddr_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnStats_14 extends _i1.SmartFake implements _i2.ConnStats {
  _FakeConnStats_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnScope_15 extends _i1.SmartFake implements _i4.ConnScope {
  _FakeConnScope_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [P2PStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2PStream<T> extends _i1.Mock implements _i3.P2PStream<T> {
  MockP2PStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Conn get conn => (super.noSuchMethod(
        Invocation.getter(#conn),
        returnValue: _FakeConn_0(
          this,
          Invocation.getter(#conn),
        ),
      ) as _i2.Conn);

  @override
  _i3.P2PStream<_i14.Uint8List> get incoming => (super.noSuchMethod(
        Invocation.getter(#incoming),
        returnValue: _FakeP2PStream_1<_i14.Uint8List>(
          this,
          Invocation.getter(#incoming),
        ),
      ) as _i3.P2PStream<_i14.Uint8List>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get isWritable => (super.noSuchMethod(
        Invocation.getter(#isWritable),
        returnValue: false,
      ) as bool);

  @override
  String id() => (super.noSuchMethod(
        Invocation.method(
          #id,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #id,
            [],
          ),
        ),
      ) as String);

  @override
  String protocol() => (super.noSuchMethod(
        Invocation.method(
          #protocol,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #protocol,
            [],
          ),
        ),
      ) as String);

  @override
  _i16.Future<void> setProtocol(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setProtocol,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i3.StreamStats stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _FakeStreamStats_2(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        ),
      ) as _i3.StreamStats);

  @override
  _i4.StreamManagementScope scope() => (super.noSuchMethod(
        Invocation.method(
          #scope,
          [],
        ),
        returnValue: _FakeStreamManagementScope_3(
          this,
          Invocation.method(
            #scope,
            [],
          ),
        ),
      ) as _i4.StreamManagementScope);

  @override
  _i16.Future<_i14.Uint8List> read([int? maxLength]) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [maxLength],
        ),
        returnValue: _i16.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i16.Future<_i14.Uint8List>);

  @override
  _i16.Future<void> write(_i14.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> closeWrite() => (super.noSuchMethod(
        Invocation.method(
          #closeWrite,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> closeRead() => (super.noSuchMethod(
        Invocation.method(
          #closeRead,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> setDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setDeadline,
          [time],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> setReadDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setReadDeadline,
          [time],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> setWriteDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setWriteDeadline,
          [time],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [CircuitV2Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockCircuitV2Client extends _i1.Mock implements _i17.CircuitV2Client {
  MockCircuitV2Client() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Host get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _FakeHost_4(
          this,
          Invocation.getter(#host),
        ),
      ) as _i5.Host);

  @override
  _i6.Upgrader get upgrader => (super.noSuchMethod(
        Invocation.getter(#upgrader),
        returnValue: _FakeUpgrader_5(
          this,
          Invocation.getter(#upgrader),
        ),
      ) as _i6.Upgrader);

  @override
  _i7.ConnManager get connManager => (super.noSuchMethod(
        Invocation.getter(#connManager),
        returnValue: _FakeConnManager_6(
          this,
          Invocation.getter(#connManager),
        ),
      ) as _i7.ConnManager);

  @override
  _i8.TransportConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeTransportConfig_7(
          this,
          Invocation.getter(#config),
        ),
      ) as _i8.TransportConfig);

  @override
  List<String> get protocols => (super.noSuchMethod(
        Invocation.getter(#protocols),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get protocolId => (super.noSuchMethod(
        Invocation.getter(#protocolId),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#protocolId),
        ),
      ) as String);

  @override
  _i9.Peerstore get peerstore => (super.noSuchMethod(
        Invocation.getter(#peerstore),
        returnValue: _FakePeerstore_8(
          this,
          Invocation.getter(#peerstore),
        ),
      ) as _i9.Peerstore);

  @override
  set onRelayPathFailed(_i17.RelayPathFailedCallback? _onRelayPathFailed) =>
      super.noSuchMethod(
        Invocation.setter(
          #onRelayPathFailed,
          _onRelayPathFailed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i10.TransportConn> dial(
    _i13.MultiAddr? addr, {
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dial,
          [addr],
          {#timeout: timeout},
        ),
        returnValue: _i16.Future<_i10.TransportConn>.value(_FakeTransportConn_9(
          this,
          Invocation.method(
            #dial,
            [addr],
            {#timeout: timeout},
          ),
        )),
      ) as _i16.Future<_i10.TransportConn>);

  @override
  _i16.Future<_i11.Listener> listen(_i13.MultiAddr? addr) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [addr],
        ),
        returnValue: _i16.Future<_i11.Listener>.value(_FakeListener_10(
          this,
          Invocation.method(
            #listen,
            [addr],
          ),
        )),
      ) as _i16.Future<_i11.Listener>);

  @override
  bool canDial(_i13.MultiAddr? addr) => (super.noSuchMethod(
        Invocation.method(
          #canDial,
          [addr],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i13.MultiAddr> listenAddrs() => (super.noSuchMethod(
        Invocation.method(
          #listenAddrs,
          [],
        ),
        returnValue: <_i13.MultiAddr>[],
      ) as List<_i13.MultiAddr>);

  @override
  dynamic transportForDial(_i13.MultiAddr? addr) =>
      super.noSuchMethod(Invocation.method(
        #transportForDial,
        [addr],
      ));

  @override
  dynamic transportForListen(_i13.MultiAddr? addr) =>
      super.noSuchMethod(Invocation.method(
        #transportForListen,
        [addr],
      ));

  @override
  bool canListen(_i13.MultiAddr? addr) => (super.noSuchMethod(
        Invocation.method(
          #canListen,
          [addr],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i16.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [Conn].
///
/// See the documentation for Mockito's code generation for more information.
class MockConn extends _i1.Mock implements _i2.Conn {
  MockConn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i16.Future<List<_i3.P2PStream<dynamic>>> get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _i16.Future<List<_i3.P2PStream<dynamic>>>.value(
            <_i3.P2PStream<dynamic>>[]),
      ) as _i16.Future<List<_i3.P2PStream<dynamic>>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i12.PeerId get localPeer => (super.noSuchMethod(
        Invocation.getter(#localPeer),
        returnValue: _FakePeerId_11(
          this,
          Invocation.getter(#localPeer),
        ),
      ) as _i12.PeerId);

  @override
  _i12.PeerId get remotePeer => (super.noSuchMethod(
        Invocation.getter(#remotePeer),
        returnValue: _FakePeerId_11(
          this,
          Invocation.getter(#remotePeer),
        ),
      ) as _i12.PeerId);

  @override
  _i16.Future<_i18.PublicKey?> get remotePublicKey => (super.noSuchMethod(
        Invocation.getter(#remotePublicKey),
        returnValue: _i16.Future<_i18.PublicKey?>.value(),
      ) as _i16.Future<_i18.PublicKey?>);

  @override
  _i2.ConnState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeConnState_12(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.ConnState);

  @override
  _i13.MultiAddr get localMultiaddr => (super.noSuchMethod(
        Invocation.getter(#localMultiaddr),
        returnValue: _FakeMultiAddr_13(
          this,
          Invocation.getter(#localMultiaddr),
        ),
      ) as _i13.MultiAddr);

  @override
  _i13.MultiAddr get remoteMultiaddr => (super.noSuchMethod(
        Invocation.getter(#remoteMultiaddr),
        returnValue: _FakeMultiAddr_13(
          this,
          Invocation.getter(#remoteMultiaddr),
        ),
      ) as _i13.MultiAddr);

  @override
  _i2.ConnStats get stat => (super.noSuchMethod(
        Invocation.getter(#stat),
        returnValue: _FakeConnStats_14(
          this,
          Invocation.getter(#stat),
        ),
      ) as _i2.ConnStats);

  @override
  _i4.ConnScope get scope => (super.noSuchMethod(
        Invocation.getter(#scope),
        returnValue: _FakeConnScope_15(
          this,
          Invocation.getter(#scope),
        ),
      ) as _i4.ConnScope);

  @override
  _i16.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);

  @override
  _i16.Future<_i3.P2PStream<dynamic>> newStream(_i19.Context? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [context],
        ),
        returnValue:
            _i16.Future<_i3.P2PStream<dynamic>>.value(_FakeP2PStream_1<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [context],
          ),
        )),
      ) as _i16.Future<_i3.P2PStream<dynamic>>);
}
