// Mocks generated by Mockito 5.4.5 from annotations
// in dart_libp2p/test/p2p/host/autorelay/autorelay_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;

import 'package:dart_libp2p/config/config.dart' as _i22;
import 'package:dart_libp2p/core/connmgr/conn_manager.dart' as _i6;
import 'package:dart_libp2p/core/event/bus.dart' as _i7;
import 'package:dart_libp2p/core/host/host.dart' as _i11;
import 'package:dart_libp2p/core/multiaddr.dart' as _i15;
import 'package:dart_libp2p/core/network/conn.dart' as _i10;
import 'package:dart_libp2p/core/network/context.dart' as _i18;
import 'package:dart_libp2p/core/network/network.dart' as _i4;
import 'package:dart_libp2p/core/network/notifiee.dart' as _i20;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i9;
import 'package:dart_libp2p/core/network/stream.dart' as _i8;
import 'package:dart_libp2p/core/network/transport_conn.dart' as _i21;
import 'package:dart_libp2p/core/peer/addr_info.dart' as _i17;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i2;
import 'package:dart_libp2p/core/peerstore.dart' as _i3;
import 'package:dart_libp2p/core/protocol/switch.dart' as _i5;
import 'package:dart_libp2p/p2p/host/autorelay/autorelay_config.dart' as _i13;
import 'package:dart_libp2p/p2p/host/autorelay/autorelay_metrics.dart' as _i14;
import 'package:dart_libp2p/p2p/host/autorelay/relay_finder.dart' as _i23;
import 'package:dart_libp2p/p2p/protocol/circuitv2/client/reservation.dart'
    as _i24;
import 'package:dart_libp2p/p2p/transport/upgrader.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerstore_1 extends _i1.SmartFake implements _i3.Peerstore {
  _FakePeerstore_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetwork_2 extends _i1.SmartFake implements _i4.Network {
  _FakeNetwork_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProtocolSwitch_3 extends _i1.SmartFake
    implements _i5.ProtocolSwitch {
  _FakeProtocolSwitch_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnManager_4 extends _i1.SmartFake implements _i6.ConnManager {
  _FakeConnManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventBus_5 extends _i1.SmartFake implements _i7.EventBus {
  _FakeEventBus_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeP2PStream_6<T> extends _i1.SmartFake implements _i8.P2PStream<T> {
  _FakeP2PStream_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscription_7<T> extends _i1.SmartFake
    implements _i7.Subscription<T> {
  _FakeSubscription_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmitter_8 extends _i1.SmartFake implements _i7.Emitter {
  _FakeEmitter_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResourceManager_9 extends _i1.SmartFake
    implements _i9.ResourceManager {
  _FakeResourceManager_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConn_10 extends _i1.SmartFake implements _i10.Conn {
  _FakeConn_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHost_11 extends _i1.SmartFake implements _i11.Host {
  _FakeHost_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpgrader_12 extends _i1.SmartFake implements _i12.Upgrader {
  _FakeUpgrader_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAutoRelayConfig_13 extends _i1.SmartFake
    implements _i13.AutoRelayConfig {
  _FakeAutoRelayConfig_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWrappedMetricsTracer_14 extends _i1.SmartFake
    implements _i14.WrappedMetricsTracer {
  _FakeWrappedMetricsTracer_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Host].
///
/// See the documentation for Mockito's code generation for more information.
class MockHost extends _i1.Mock implements _i11.Host {
  MockHost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PeerId get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakePeerId_0(this, Invocation.getter(#id)),
          )
          as _i2.PeerId);

  @override
  _i3.Peerstore get peerStore =>
      (super.noSuchMethod(
            Invocation.getter(#peerStore),
            returnValue: _FakePeerstore_1(this, Invocation.getter(#peerStore)),
          )
          as _i3.Peerstore);

  @override
  List<_i15.MultiAddr> get addrs =>
      (super.noSuchMethod(
            Invocation.getter(#addrs),
            returnValue: <_i15.MultiAddr>[],
          )
          as List<_i15.MultiAddr>);

  @override
  _i4.Network get network =>
      (super.noSuchMethod(
            Invocation.getter(#network),
            returnValue: _FakeNetwork_2(this, Invocation.getter(#network)),
          )
          as _i4.Network);

  @override
  _i5.ProtocolSwitch get mux =>
      (super.noSuchMethod(
            Invocation.getter(#mux),
            returnValue: _FakeProtocolSwitch_3(this, Invocation.getter(#mux)),
          )
          as _i5.ProtocolSwitch);

  @override
  _i6.ConnManager get connManager =>
      (super.noSuchMethod(
            Invocation.getter(#connManager),
            returnValue: _FakeConnManager_4(
              this,
              Invocation.getter(#connManager),
            ),
          )
          as _i6.ConnManager);

  @override
  _i7.EventBus get eventBus =>
      (super.noSuchMethod(
            Invocation.getter(#eventBus),
            returnValue: _FakeEventBus_5(this, Invocation.getter(#eventBus)),
          )
          as _i7.EventBus);

  @override
  _i16.Future<void> connect(_i17.AddrInfo? pi, {_i18.Context? context}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [pi], {#context: context}),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void setStreamHandler(String? pid, _i4.StreamHandler? handler) =>
      super.noSuchMethod(
        Invocation.method(#setStreamHandler, [pid, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void setStreamHandlerMatch(
    String? pid,
    bool Function(String)? match,
    _i4.StreamHandler? handler,
  ) => super.noSuchMethod(
    Invocation.method(#setStreamHandlerMatch, [pid, match, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeStreamHandler(String? pid) => super.noSuchMethod(
    Invocation.method(#removeStreamHandler, [pid]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<_i8.P2PStream<dynamic>> newStream(
    _i2.PeerId? p,
    List<String>? pids,
    _i18.Context? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#newStream, [p, pids, context]),
            returnValue: _i16.Future<_i8.P2PStream<dynamic>>.value(
              _FakeP2PStream_6<dynamic>(
                this,
                Invocation.method(#newStream, [p, pids, context]),
              ),
            ),
          )
          as _i16.Future<_i8.P2PStream<dynamic>>);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [EventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventBus extends _i1.Mock implements _i7.EventBus {
  MockEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Subscription<dynamic> subscribe(
    Object? eventType, {
    List<_i7.SubscriptionOpt>? opts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [eventType], {#opts: opts}),
            returnValue: _FakeSubscription_7<dynamic>(
              this,
              Invocation.method(#subscribe, [eventType], {#opts: opts}),
            ),
          )
          as _i7.Subscription<dynamic>);

  @override
  _i16.Future<_i7.Emitter> emitter(
    dynamic eventType, {
    List<_i7.EmitterOpt>? opts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#emitter, [eventType], {#opts: opts}),
            returnValue: _i16.Future<_i7.Emitter>.value(
              _FakeEmitter_8(
                this,
                Invocation.method(#emitter, [eventType], {#opts: opts}),
              ),
            ),
          )
          as _i16.Future<_i7.Emitter>);

  @override
  List<String> getAllEventTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEventTypes, []),
            returnValue: <String>[],
          )
          as List<String>);
}

/// A class which mocks [Emitter].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmitter extends _i1.Mock implements _i7.Emitter {
  MockEmitter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<void> emit(Object? event) =>
      (super.noSuchMethod(
            Invocation.method(#emit, [event]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [Subscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscription<T> extends _i1.Mock implements _i7.Subscription<T> {
  MockSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Stream<T> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<T>.empty(),
          )
          as _i16.Stream<T>);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [Network].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetwork extends _i1.Mock implements _i4.Network {
  MockNetwork() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i15.MultiAddr> get listenAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listenAddresses),
            returnValue: <_i15.MultiAddr>[],
          )
          as List<_i15.MultiAddr>);

  @override
  _i16.Future<List<_i15.MultiAddr>> get interfaceListenAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#interfaceListenAddresses),
            returnValue: _i16.Future<List<_i15.MultiAddr>>.value(
              <_i15.MultiAddr>[],
            ),
          )
          as _i16.Future<List<_i15.MultiAddr>>);

  @override
  _i9.ResourceManager get resourceManager =>
      (super.noSuchMethod(
            Invocation.getter(#resourceManager),
            returnValue: _FakeResourceManager_9(
              this,
              Invocation.getter(#resourceManager),
            ),
          )
          as _i9.ResourceManager);

  @override
  _i3.Peerstore get peerstore =>
      (super.noSuchMethod(
            Invocation.getter(#peerstore),
            returnValue: _FakePeerstore_1(this, Invocation.getter(#peerstore)),
          )
          as _i3.Peerstore);

  @override
  _i2.PeerId get localPeer =>
      (super.noSuchMethod(
            Invocation.getter(#localPeer),
            returnValue: _FakePeerId_0(this, Invocation.getter(#localPeer)),
          )
          as _i2.PeerId);

  @override
  List<_i2.PeerId> get peers =>
      (super.noSuchMethod(
            Invocation.getter(#peers),
            returnValue: <_i2.PeerId>[],
          )
          as List<_i2.PeerId>);

  @override
  List<_i10.Conn> get conns =>
      (super.noSuchMethod(Invocation.getter(#conns), returnValue: <_i10.Conn>[])
          as List<_i10.Conn>);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void setStreamHandler(
    String? protocol,
    _i16.Future<void> Function(dynamic, _i2.PeerId)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#setStreamHandler, [protocol, handler]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<_i8.P2PStream<dynamic>> newStream(
    _i18.Context? context,
    _i2.PeerId? peerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#newStream, [context, peerId]),
            returnValue: _i16.Future<_i8.P2PStream<dynamic>>.value(
              _FakeP2PStream_6<dynamic>(
                this,
                Invocation.method(#newStream, [context, peerId]),
              ),
            ),
          )
          as _i16.Future<_i8.P2PStream<dynamic>>);

  @override
  _i16.Future<void> listen(List<_i15.MultiAddr>? addrs) =>
      (super.noSuchMethod(
            Invocation.method(#listen, [addrs]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i10.Conn> dialPeer(_i18.Context? context, _i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#dialPeer, [context, peerId]),
            returnValue: _i16.Future<_i10.Conn>.value(
              _FakeConn_10(
                this,
                Invocation.method(#dialPeer, [context, peerId]),
              ),
            ),
          )
          as _i16.Future<_i10.Conn>);

  @override
  _i16.Future<void> closePeer(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#closePeer, [peerId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i4.Connectedness connectedness(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#connectedness, [peerId]),
            returnValue: _i4.Connectedness.notConnected,
          )
          as _i4.Connectedness);

  @override
  List<_i10.Conn> connsToPeer(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#connsToPeer, [peerId]),
            returnValue: <_i10.Conn>[],
          )
          as List<_i10.Conn>);

  @override
  void notify(_i20.Notifiee? notifiee) => super.noSuchMethod(
    Invocation.method(#notify, [notifiee]),
    returnValueForMissingStub: null,
  );

  @override
  void stopNotify(_i20.Notifiee? notifiee) => super.noSuchMethod(
    Invocation.method(#stopNotify, [notifiee]),
    returnValueForMissingStub: null,
  );

  @override
  bool canDial(_i2.PeerId? peerId, _i15.MultiAddr? addr) =>
      (super.noSuchMethod(
            Invocation.method(#canDial, [peerId, addr]),
            returnValue: false,
          )
          as bool);

  @override
  void removeListenAddress(_i15.MultiAddr? addr) => super.noSuchMethod(
    Invocation.method(#removeListenAddress, [addr]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Upgrader].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpgrader extends _i1.Mock implements _i12.Upgrader {
  MockUpgrader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i10.Conn> upgradeOutbound({
    required _i21.TransportConn? connection,
    required _i2.PeerId? remotePeerId,
    required _i22.Config? config,
    required _i15.MultiAddr? remoteAddr,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeOutbound, [], {
              #connection: connection,
              #remotePeerId: remotePeerId,
              #config: config,
              #remoteAddr: remoteAddr,
            }),
            returnValue: _i16.Future<_i10.Conn>.value(
              _FakeConn_10(
                this,
                Invocation.method(#upgradeOutbound, [], {
                  #connection: connection,
                  #remotePeerId: remotePeerId,
                  #config: config,
                  #remoteAddr: remoteAddr,
                }),
              ),
            ),
          )
          as _i16.Future<_i10.Conn>);

  @override
  _i16.Future<_i10.Conn> upgradeInbound({
    required _i21.TransportConn? connection,
    required _i22.Config? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeInbound, [], {
              #connection: connection,
              #config: config,
            }),
            returnValue: _i16.Future<_i10.Conn>.value(
              _FakeConn_10(
                this,
                Invocation.method(#upgradeInbound, [], {
                  #connection: connection,
                  #config: config,
                }),
              ),
            ),
          )
          as _i16.Future<_i10.Conn>);
}

/// A class which mocks [RelayFinder].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayFinder extends _i1.Mock implements _i23.RelayFinder {
  MockRelayFinder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Host get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _FakeHost_11(this, Invocation.getter(#host)),
          )
          as _i11.Host);

  @override
  _i12.Upgrader get upgrader =>
      (super.noSuchMethod(
            Invocation.getter(#upgrader),
            returnValue: _FakeUpgrader_12(this, Invocation.getter(#upgrader)),
          )
          as _i12.Upgrader);

  @override
  _i13.AutoRelayConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeAutoRelayConfig_13(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i13.AutoRelayConfig);

  @override
  _i14.WrappedMetricsTracer get metricsTracer =>
      (super.noSuchMethod(
            Invocation.getter(#metricsTracer),
            returnValue: _FakeWrappedMetricsTracer_14(
              this,
              Invocation.getter(#metricsTracer),
            ),
          )
          as _i14.WrappedMetricsTracer);

  @override
  _i16.Stream<void> get onRelaysUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onRelaysUpdated),
            returnValue: _i16.Stream<void>.empty(),
          )
          as _i16.Stream<void>);

  @override
  _i16.Future<int> get relayCount =>
      (super.noSuchMethod(
            Invocation.getter(#relayCount),
            returnValue: _i16.Future<int>.value(0),
          )
          as _i16.Future<int>);

  @override
  _i16.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<List<_i15.MultiAddr>> getRelayAddrs(
    List<_i15.MultiAddr>? currentHostAddrs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRelayAddrs, [currentHostAddrs]),
            returnValue: _i16.Future<List<_i15.MultiAddr>>.value(
              <_i15.MultiAddr>[],
            ),
          )
          as _i16.Future<List<_i15.MultiAddr>>);

  @override
  _i16.Future<void> addTestReservation(
    _i2.PeerId? relayPeerId,
    _i24.Reservation? reservation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTestReservation, [relayPeerId, reservation]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool> hasRelay(_i2.PeerId? relayPeerId) =>
      (super.noSuchMethod(
            Invocation.method(#hasRelay, [relayPeerId]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}
