// Mocks generated by Mockito 5.4.5 from annotations
// in dart_libp2p/test/p2p/host/autorelay/relay_finder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:dart_libp2p/config/config.dart' as _i20;
import 'package:dart_libp2p/core/connmgr/conn_manager.dart' as _i6;
import 'package:dart_libp2p/core/event/bus.dart' as _i7;
import 'package:dart_libp2p/core/host/host.dart' as _i12;
import 'package:dart_libp2p/core/multiaddr.dart' as _i13;
import 'package:dart_libp2p/core/network/conn.dart' as _i11;
import 'package:dart_libp2p/core/network/context.dart' as _i15;
import 'package:dart_libp2p/core/network/network.dart' as _i4;
import 'package:dart_libp2p/core/network/notifiee.dart' as _i17;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i10;
import 'package:dart_libp2p/core/network/stream.dart' as _i8;
import 'package:dart_libp2p/core/network/transport_conn.dart' as _i19;
import 'package:dart_libp2p/core/peer/addr_info.dart' as _i9;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i2;
import 'package:dart_libp2p/core/peerstore.dart' as _i3;
import 'package:dart_libp2p/core/protocol/switch.dart' as _i5;
import 'package:dart_libp2p/p2p/discovery/peer_info.dart' as _i16;
import 'package:dart_libp2p/p2p/transport/upgrader.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerstore_1 extends _i1.SmartFake implements _i3.Peerstore {
  _FakePeerstore_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetwork_2 extends _i1.SmartFake implements _i4.Network {
  _FakeNetwork_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProtocolSwitch_3 extends _i1.SmartFake
    implements _i5.ProtocolSwitch {
  _FakeProtocolSwitch_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConnManager_4 extends _i1.SmartFake implements _i6.ConnManager {
  _FakeConnManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEventBus_5 extends _i1.SmartFake implements _i7.EventBus {
  _FakeEventBus_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeP2PStream_6<T> extends _i1.SmartFake implements _i8.P2PStream<T> {
  _FakeP2PStream_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddrBook_7 extends _i1.SmartFake implements _i3.AddrBook {
  _FakeAddrBook_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeyBook_8 extends _i1.SmartFake implements _i3.KeyBook {
  _FakeKeyBook_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerMetadata_9 extends _i1.SmartFake implements _i3.PeerMetadata {
  _FakePeerMetadata_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetrics_10 extends _i1.SmartFake implements _i3.Metrics {
  _FakeMetrics_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProtoBook_11 extends _i1.SmartFake implements _i3.ProtoBook {
  _FakeProtoBook_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddrInfo_12 extends _i1.SmartFake implements _i9.AddrInfo {
  _FakeAddrInfo_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubscription_13<T> extends _i1.SmartFake
    implements _i7.Subscription<T> {
  _FakeSubscription_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmitter_14 extends _i1.SmartFake implements _i7.Emitter {
  _FakeEmitter_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResourceManager_15 extends _i1.SmartFake
    implements _i10.ResourceManager {
  _FakeResourceManager_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConn_16 extends _i1.SmartFake implements _i11.Conn {
  _FakeConn_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Host].
///
/// See the documentation for Mockito's code generation for more information.
class MockHost extends _i1.Mock implements _i12.Host {
  MockHost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PeerId get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakePeerId_0(this, Invocation.getter(#id)),
          )
          as _i2.PeerId);

  @override
  _i3.Peerstore get peerStore =>
      (super.noSuchMethod(
            Invocation.getter(#peerStore),
            returnValue: _FakePeerstore_1(this, Invocation.getter(#peerStore)),
          )
          as _i3.Peerstore);

  @override
  List<_i13.MultiAddr> get addrs =>
      (super.noSuchMethod(
            Invocation.getter(#addrs),
            returnValue: <_i13.MultiAddr>[],
          )
          as List<_i13.MultiAddr>);

  @override
  _i4.Network get network =>
      (super.noSuchMethod(
            Invocation.getter(#network),
            returnValue: _FakeNetwork_2(this, Invocation.getter(#network)),
          )
          as _i4.Network);

  @override
  _i5.ProtocolSwitch get mux =>
      (super.noSuchMethod(
            Invocation.getter(#mux),
            returnValue: _FakeProtocolSwitch_3(this, Invocation.getter(#mux)),
          )
          as _i5.ProtocolSwitch);

  @override
  _i6.ConnManager get connManager =>
      (super.noSuchMethod(
            Invocation.getter(#connManager),
            returnValue: _FakeConnManager_4(
              this,
              Invocation.getter(#connManager),
            ),
          )
          as _i6.ConnManager);

  @override
  _i7.EventBus get eventBus =>
      (super.noSuchMethod(
            Invocation.getter(#eventBus),
            returnValue: _FakeEventBus_5(this, Invocation.getter(#eventBus)),
          )
          as _i7.EventBus);

  @override
  _i14.Future<void> connect(_i9.AddrInfo? pi, {_i15.Context? context}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [pi], {#context: context}),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void setStreamHandler(String? pid, _i4.StreamHandler? handler) =>
      super.noSuchMethod(
        Invocation.method(#setStreamHandler, [pid, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void setStreamHandlerMatch(
    String? pid,
    bool Function(String)? match,
    _i4.StreamHandler? handler,
  ) => super.noSuchMethod(
    Invocation.method(#setStreamHandlerMatch, [pid, match, handler]),
    returnValueForMissingStub: null,
  );

  @override
  void removeStreamHandler(String? pid) => super.noSuchMethod(
    Invocation.method(#removeStreamHandler, [pid]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<_i8.P2PStream<dynamic>> newStream(
    _i2.PeerId? p,
    List<String>? pids,
    _i15.Context? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#newStream, [p, pids, context]),
            returnValue: _i14.Future<_i8.P2PStream<dynamic>>.value(
              _FakeP2PStream_6<dynamic>(
                this,
                Invocation.method(#newStream, [p, pids, context]),
              ),
            ),
          )
          as _i14.Future<_i8.P2PStream<dynamic>>);

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}

/// A class which mocks [Peerstore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerstore extends _i1.Mock implements _i3.Peerstore {
  MockPeerstore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AddrBook get addrBook =>
      (super.noSuchMethod(
            Invocation.getter(#addrBook),
            returnValue: _FakeAddrBook_7(this, Invocation.getter(#addrBook)),
          )
          as _i3.AddrBook);

  @override
  _i3.KeyBook get keyBook =>
      (super.noSuchMethod(
            Invocation.getter(#keyBook),
            returnValue: _FakeKeyBook_8(this, Invocation.getter(#keyBook)),
          )
          as _i3.KeyBook);

  @override
  _i3.PeerMetadata get peerMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#peerMetadata),
            returnValue: _FakePeerMetadata_9(
              this,
              Invocation.getter(#peerMetadata),
            ),
          )
          as _i3.PeerMetadata);

  @override
  _i3.Metrics get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeMetrics_10(this, Invocation.getter(#metrics)),
          )
          as _i3.Metrics);

  @override
  _i3.ProtoBook get protoBook =>
      (super.noSuchMethod(
            Invocation.getter(#protoBook),
            returnValue: _FakeProtoBook_11(this, Invocation.getter(#protoBook)),
          )
          as _i3.ProtoBook);

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i9.AddrInfo> peerInfo(_i2.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#peerInfo, [id]),
            returnValue: _i14.Future<_i9.AddrInfo>.value(
              _FakeAddrInfo_12(this, Invocation.method(#peerInfo, [id])),
            ),
          )
          as _i14.Future<_i9.AddrInfo>);

  @override
  _i14.Future<List<_i2.PeerId>> peers() =>
      (super.noSuchMethod(
            Invocation.method(#peers, []),
            returnValue: _i14.Future<List<_i2.PeerId>>.value(<_i2.PeerId>[]),
          )
          as _i14.Future<List<_i2.PeerId>>);

  @override
  _i14.Future<void> removePeer(_i2.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#removePeer, [id]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> addOrUpdatePeer(
    _i2.PeerId? peerId, {
    List<_i13.MultiAddr>? addrs,
    List<String>? protocols,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addOrUpdatePeer,
              [peerId],
              {#addrs: addrs, #protocols: protocols, #metadata: metadata},
            ),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i16.PeerInfo?> getPeer(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPeer, [peerId]),
            returnValue: _i14.Future<_i16.PeerInfo?>.value(),
          )
          as _i14.Future<_i16.PeerInfo?>);
}

/// A class which mocks [AddrBook].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddrBook extends _i1.Mock implements _i3.AddrBook {
  MockAddrBook() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<void> addAddr(
    _i2.PeerId? p,
    _i13.MultiAddr? addr,
    Duration? ttl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAddr, [p, addr, ttl]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> addAddrs(
    _i2.PeerId? p,
    List<_i13.MultiAddr>? addrs,
    Duration? ttl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAddrs, [p, addrs, ttl]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> setAddr(
    _i2.PeerId? p,
    _i13.MultiAddr? addr,
    Duration? ttl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAddr, [p, addr, ttl]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> setAddrs(
    _i2.PeerId? p,
    List<_i13.MultiAddr>? addrs,
    Duration? ttl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAddrs, [p, addrs, ttl]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> updateAddrs(
    _i2.PeerId? p,
    Duration? oldTTL,
    Duration? newTTL,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddrs, [p, oldTTL, newTTL]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<List<_i13.MultiAddr>> addrs(_i2.PeerId? p) =>
      (super.noSuchMethod(
            Invocation.method(#addrs, [p]),
            returnValue: _i14.Future<List<_i13.MultiAddr>>.value(
              <_i13.MultiAddr>[],
            ),
          )
          as _i14.Future<List<_i13.MultiAddr>>);

  @override
  _i14.Future<_i14.Stream<_i13.MultiAddr>> addrStream(_i2.PeerId? id) =>
      (super.noSuchMethod(
            Invocation.method(#addrStream, [id]),
            returnValue: _i14.Future<_i14.Stream<_i13.MultiAddr>>.value(
              _i14.Stream<_i13.MultiAddr>.empty(),
            ),
          )
          as _i14.Future<_i14.Stream<_i13.MultiAddr>>);

  @override
  _i14.Future<void> clearAddrs(_i2.PeerId? p) =>
      (super.noSuchMethod(
            Invocation.method(#clearAddrs, [p]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<List<_i2.PeerId>> peersWithAddrs() =>
      (super.noSuchMethod(
            Invocation.method(#peersWithAddrs, []),
            returnValue: _i14.Future<List<_i2.PeerId>>.value(<_i2.PeerId>[]),
          )
          as _i14.Future<List<_i2.PeerId>>);
}

/// A class which mocks [EventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventBus extends _i1.Mock implements _i7.EventBus {
  MockEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Subscription<dynamic> subscribe(
    Object? eventType, {
    List<_i7.SubscriptionOpt>? opts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [eventType], {#opts: opts}),
            returnValue: _FakeSubscription_13<dynamic>(
              this,
              Invocation.method(#subscribe, [eventType], {#opts: opts}),
            ),
          )
          as _i7.Subscription<dynamic>);

  @override
  _i14.Future<_i7.Emitter> emitter(
    dynamic eventType, {
    List<_i7.EmitterOpt>? opts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#emitter, [eventType], {#opts: opts}),
            returnValue: _i14.Future<_i7.Emitter>.value(
              _FakeEmitter_14(
                this,
                Invocation.method(#emitter, [eventType], {#opts: opts}),
              ),
            ),
          )
          as _i14.Future<_i7.Emitter>);

  @override
  List<String> getAllEventTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEventTypes, []),
            returnValue: <String>[],
          )
          as List<String>);
}

/// A class which mocks [Network].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetwork extends _i1.Mock implements _i4.Network {
  MockNetwork() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i13.MultiAddr> get listenAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#listenAddresses),
            returnValue: <_i13.MultiAddr>[],
          )
          as List<_i13.MultiAddr>);

  @override
  _i14.Future<List<_i13.MultiAddr>> get interfaceListenAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#interfaceListenAddresses),
            returnValue: _i14.Future<List<_i13.MultiAddr>>.value(
              <_i13.MultiAddr>[],
            ),
          )
          as _i14.Future<List<_i13.MultiAddr>>);

  @override
  _i10.ResourceManager get resourceManager =>
      (super.noSuchMethod(
            Invocation.getter(#resourceManager),
            returnValue: _FakeResourceManager_15(
              this,
              Invocation.getter(#resourceManager),
            ),
          )
          as _i10.ResourceManager);

  @override
  _i3.Peerstore get peerstore =>
      (super.noSuchMethod(
            Invocation.getter(#peerstore),
            returnValue: _FakePeerstore_1(this, Invocation.getter(#peerstore)),
          )
          as _i3.Peerstore);

  @override
  _i2.PeerId get localPeer =>
      (super.noSuchMethod(
            Invocation.getter(#localPeer),
            returnValue: _FakePeerId_0(this, Invocation.getter(#localPeer)),
          )
          as _i2.PeerId);

  @override
  List<_i2.PeerId> get peers =>
      (super.noSuchMethod(
            Invocation.getter(#peers),
            returnValue: <_i2.PeerId>[],
          )
          as List<_i2.PeerId>);

  @override
  List<_i11.Conn> get conns =>
      (super.noSuchMethod(Invocation.getter(#conns), returnValue: <_i11.Conn>[])
          as List<_i11.Conn>);

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void setStreamHandler(
    String? protocol,
    _i14.Future<void> Function(dynamic, _i2.PeerId)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#setStreamHandler, [protocol, handler]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<_i8.P2PStream<dynamic>> newStream(
    _i15.Context? context,
    _i2.PeerId? peerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#newStream, [context, peerId]),
            returnValue: _i14.Future<_i8.P2PStream<dynamic>>.value(
              _FakeP2PStream_6<dynamic>(
                this,
                Invocation.method(#newStream, [context, peerId]),
              ),
            ),
          )
          as _i14.Future<_i8.P2PStream<dynamic>>);

  @override
  _i14.Future<void> listen(List<_i13.MultiAddr>? addrs) =>
      (super.noSuchMethod(
            Invocation.method(#listen, [addrs]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<_i11.Conn> dialPeer(_i15.Context? context, _i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#dialPeer, [context, peerId]),
            returnValue: _i14.Future<_i11.Conn>.value(
              _FakeConn_16(
                this,
                Invocation.method(#dialPeer, [context, peerId]),
              ),
            ),
          )
          as _i14.Future<_i11.Conn>);

  @override
  _i14.Future<void> closePeer(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#closePeer, [peerId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i4.Connectedness connectedness(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#connectedness, [peerId]),
            returnValue: _i4.Connectedness.notConnected,
          )
          as _i4.Connectedness);

  @override
  List<_i11.Conn> connsToPeer(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
            Invocation.method(#connsToPeer, [peerId]),
            returnValue: <_i11.Conn>[],
          )
          as List<_i11.Conn>);

  @override
  void notify(_i17.Notifiee? notifiee) => super.noSuchMethod(
    Invocation.method(#notify, [notifiee]),
    returnValueForMissingStub: null,
  );

  @override
  void stopNotify(_i17.Notifiee? notifiee) => super.noSuchMethod(
    Invocation.method(#stopNotify, [notifiee]),
    returnValueForMissingStub: null,
  );

  @override
  bool canDial(_i2.PeerId? peerId, _i13.MultiAddr? addr) =>
      (super.noSuchMethod(
            Invocation.method(#canDial, [peerId, addr]),
            returnValue: false,
          )
          as bool);

  @override
  void removeListenAddress(_i13.MultiAddr? addr) => super.noSuchMethod(
    Invocation.method(#removeListenAddress, [addr]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Upgrader].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpgrader extends _i1.Mock implements _i18.Upgrader {
  MockUpgrader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i11.Conn> upgradeOutbound({
    required _i19.TransportConn? connection,
    required _i2.PeerId? remotePeerId,
    required _i20.Config? config,
    required _i13.MultiAddr? remoteAddr,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeOutbound, [], {
              #connection: connection,
              #remotePeerId: remotePeerId,
              #config: config,
              #remoteAddr: remoteAddr,
            }),
            returnValue: _i14.Future<_i11.Conn>.value(
              _FakeConn_16(
                this,
                Invocation.method(#upgradeOutbound, [], {
                  #connection: connection,
                  #remotePeerId: remotePeerId,
                  #config: config,
                  #remoteAddr: remoteAddr,
                }),
              ),
            ),
          )
          as _i14.Future<_i11.Conn>);

  @override
  _i14.Future<_i11.Conn> upgradeInbound({
    required _i19.TransportConn? connection,
    required _i20.Config? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeInbound, [], {
              #connection: connection,
              #config: config,
            }),
            returnValue: _i14.Future<_i11.Conn>.value(
              _FakeConn_16(
                this,
                Invocation.method(#upgradeInbound, [], {
                  #connection: connection,
                  #config: config,
                }),
              ),
            ),
          )
          as _i14.Future<_i11.Conn>);
}
