// Mocks generated by Mockito 5.4.6 from annotations
// in dart_libp2p/test/protocol/circuitv2/client/client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;
import 'dart:typed_data' as _i21;

import 'package:dart_libp2p/config/config.dart' as _i19;
import 'package:dart_libp2p/core/connmgr/conn_manager.dart' as _i6;
import 'package:dart_libp2p/core/crypto/keys.dart' as _i23;
import 'package:dart_libp2p/core/event/bus.dart' as _i7;
import 'package:dart_libp2p/core/host/host.dart' as _i14;
import 'package:dart_libp2p/core/multiaddr.dart' as _i12;
import 'package:dart_libp2p/core/network/conn.dart' as _i9;
import 'package:dart_libp2p/core/network/context.dart' as _i16;
import 'package:dart_libp2p/core/network/network.dart' as _i4;
import 'package:dart_libp2p/core/network/notifiee.dart' as _i10;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i11;
import 'package:dart_libp2p/core/network/stream.dart' as _i8;
import 'package:dart_libp2p/core/network/transport_conn.dart' as _i18;
import 'package:dart_libp2p/core/peer/addr_info.dart' as _i13;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i2;
import 'package:dart_libp2p/core/peerstore.dart' as _i3;
import 'package:dart_libp2p/core/protocol/switch.dart' as _i5;
import 'package:dart_libp2p/p2p/discovery/peer_info.dart' as _i24;
import 'package:dart_libp2p/p2p/transport/connection_state.dart' as _i20;
import 'package:dart_libp2p/p2p/transport/upgrader.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerstore_1 extends _i1.SmartFake implements _i3.Peerstore {
  _FakePeerstore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetwork_2 extends _i1.SmartFake implements _i4.Network {
  _FakeNetwork_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtocolSwitch_3 extends _i1.SmartFake
    implements _i5.ProtocolSwitch {
  _FakeProtocolSwitch_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnManager_4 extends _i1.SmartFake implements _i6.ConnManager {
  _FakeConnManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventBus_5 extends _i1.SmartFake implements _i7.EventBus {
  _FakeEventBus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeP2PStream_6<T> extends _i1.SmartFake implements _i8.P2PStream<T> {
  _FakeP2PStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConn_7 extends _i1.SmartFake implements _i9.Conn {
  _FakeConn_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotifiee_8 extends _i1.SmartFake implements _i10.Notifiee {
  _FakeNotifiee_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamStats_9 extends _i1.SmartFake implements _i8.StreamStats {
  _FakeStreamStats_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamManagementScope_10 extends _i1.SmartFake
    implements _i11.StreamManagementScope {
  _FakeStreamManagementScope_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnState_11 extends _i1.SmartFake implements _i9.ConnState {
  _FakeConnState_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiAddr_12 extends _i1.SmartFake implements _i12.MultiAddr {
  _FakeMultiAddr_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnStats_13 extends _i1.SmartFake implements _i9.ConnStats {
  _FakeConnStats_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnScope_14 extends _i1.SmartFake implements _i11.ConnScope {
  _FakeConnScope_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddrBook_15 extends _i1.SmartFake implements _i3.AddrBook {
  _FakeAddrBook_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyBook_16 extends _i1.SmartFake implements _i3.KeyBook {
  _FakeKeyBook_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerMetadata_17 extends _i1.SmartFake implements _i3.PeerMetadata {
  _FakePeerMetadata_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetrics_18 extends _i1.SmartFake implements _i3.Metrics {
  _FakeMetrics_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtoBook_19 extends _i1.SmartFake implements _i3.ProtoBook {
  _FakeProtoBook_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddrInfo_20 extends _i1.SmartFake implements _i13.AddrInfo {
  _FakeAddrInfo_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Host].
///
/// See the documentation for Mockito's code generation for more information.
class MockHost extends _i1.Mock implements _i14.Host {
  MockHost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PeerId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.PeerId);

  @override
  _i3.Peerstore get peerStore => (super.noSuchMethod(
        Invocation.getter(#peerStore),
        returnValue: _FakePeerstore_1(
          this,
          Invocation.getter(#peerStore),
        ),
      ) as _i3.Peerstore);

  @override
  List<_i12.MultiAddr> get addrs => (super.noSuchMethod(
        Invocation.getter(#addrs),
        returnValue: <_i12.MultiAddr>[],
      ) as List<_i12.MultiAddr>);

  @override
  _i4.Network get network => (super.noSuchMethod(
        Invocation.getter(#network),
        returnValue: _FakeNetwork_2(
          this,
          Invocation.getter(#network),
        ),
      ) as _i4.Network);

  @override
  _i5.ProtocolSwitch get mux => (super.noSuchMethod(
        Invocation.getter(#mux),
        returnValue: _FakeProtocolSwitch_3(
          this,
          Invocation.getter(#mux),
        ),
      ) as _i5.ProtocolSwitch);

  @override
  _i6.ConnManager get connManager => (super.noSuchMethod(
        Invocation.getter(#connManager),
        returnValue: _FakeConnManager_4(
          this,
          Invocation.getter(#connManager),
        ),
      ) as _i6.ConnManager);

  @override
  _i7.EventBus get eventBus => (super.noSuchMethod(
        Invocation.getter(#eventBus),
        returnValue: _FakeEventBus_5(
          this,
          Invocation.getter(#eventBus),
        ),
      ) as _i7.EventBus);

  @override
  _i15.Future<void> connect(
    _i13.AddrInfo? pi, {
    _i16.Context? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [pi],
          {#context: context},
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  void setStreamHandler(
    String? pid,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandler,
          [
            pid,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStreamHandlerMatch(
    String? pid,
    bool Function(String)? match,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandlerMatch,
          [
            pid,
            match,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeStreamHandler(String? pid) => super.noSuchMethod(
        Invocation.method(
          #removeStreamHandler,
          [pid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<_i8.P2PStream<dynamic>> newStream(
    _i2.PeerId? p,
    List<String>? pids,
    _i16.Context? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [
            p,
            pids,
            context,
          ],
        ),
        returnValue:
            _i15.Future<_i8.P2PStream<dynamic>>.value(_FakeP2PStream_6<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [
              p,
              pids,
              context,
            ],
          ),
        )),
      ) as _i15.Future<_i8.P2PStream<dynamic>>);

  @override
  _i15.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
}

/// A class which mocks [Upgrader].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpgrader extends _i1.Mock implements _i17.Upgrader {
  MockUpgrader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i9.Conn> upgradeOutbound({
    required _i18.TransportConn? connection,
    required _i2.PeerId? remotePeerId,
    required _i19.Config? config,
    required _i12.MultiAddr? remoteAddr,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upgradeOutbound,
          [],
          {
            #connection: connection,
            #remotePeerId: remotePeerId,
            #config: config,
            #remoteAddr: remoteAddr,
          },
        ),
        returnValue: _i15.Future<_i9.Conn>.value(_FakeConn_7(
          this,
          Invocation.method(
            #upgradeOutbound,
            [],
            {
              #connection: connection,
              #remotePeerId: remotePeerId,
              #config: config,
              #remoteAddr: remoteAddr,
            },
          ),
        )),
      ) as _i15.Future<_i9.Conn>);

  @override
  _i15.Future<_i9.Conn> upgradeInbound({
    required _i18.TransportConn? connection,
    required _i19.Config? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upgradeInbound,
          [],
          {
            #connection: connection,
            #config: config,
          },
        ),
        returnValue: _i15.Future<_i9.Conn>.value(_FakeConn_7(
          this,
          Invocation.method(
            #upgradeInbound,
            [],
            {
              #connection: connection,
              #config: config,
            },
          ),
        )),
      ) as _i15.Future<_i9.Conn>);
}

/// A class which mocks [ConnManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnManager extends _i1.Mock implements _i6.ConnManager {
  MockConnManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Notifiee get notifiee => (super.noSuchMethod(
        Invocation.getter(#notifiee),
        returnValue: _FakeNotifiee_8(
          this,
          Invocation.getter(#notifiee),
        ),
      ) as _i10.Notifiee);

  @override
  void tagPeer(
    _i2.PeerId? peerId,
    String? tag,
    int? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #tagPeer,
          [
            peerId,
            tag,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void untagPeer(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #untagPeer,
          [
            peerId,
            tag,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void upsertTag(
    _i2.PeerId? peerId,
    String? tag,
    int Function(int)? upsert,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #upsertTag,
          [
            peerId,
            tag,
            upsert,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.TagInfo? getTagInfo(_i2.PeerId? peerId) =>
      (super.noSuchMethod(Invocation.method(
        #getTagInfo,
        [peerId],
      )) as _i6.TagInfo?);

  @override
  _i15.Future<void> trimOpenConns() => (super.noSuchMethod(
        Invocation.method(
          #trimOpenConns,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  void protect(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #protect,
          [
            peerId,
            tag,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool unprotect(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unprotect,
          [
            peerId,
            tag,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isProtected(
    _i2.PeerId? peerId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isProtected,
          [
            peerId,
            tag,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  String? checkLimit(_i6.GetConnLimiter? limiter) =>
      (super.noSuchMethod(Invocation.method(
        #checkLimit,
        [limiter],
      )) as String?);

  @override
  _i15.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  void registerConnection(_i18.TransportConn? conn) => super.noSuchMethod(
        Invocation.method(
          #registerConnection,
          [conn],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateState(
    _i18.TransportConn? conn,
    _i20.ConnectionState? state, {
    required Object? error,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateState,
          [
            conn,
            state,
          ],
          {#error: error},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.ConnectionState? getState(_i18.TransportConn? conn) =>
      (super.noSuchMethod(Invocation.method(
        #getState,
        [conn],
      )) as _i20.ConnectionState?);

  @override
  void recordActivity(_i18.TransportConn? tcpConnection) => super.noSuchMethod(
        Invocation.method(
          #recordActivity,
          [tcpConnection],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Stream<_i20.ConnectionStateChange>? getStateStream(
          _i18.TransportConn? conn) =>
      (super.noSuchMethod(Invocation.method(
        #getStateStream,
        [conn],
      )) as _i15.Stream<_i20.ConnectionStateChange>?);

  @override
  _i15.Future<void> closeConnection(_i18.TransportConn? conn) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeConnection,
          [conn],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
}

/// A class which mocks [P2PStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2PStream<T> extends _i1.Mock implements _i8.P2PStream<T> {
  MockP2PStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Conn get conn => (super.noSuchMethod(
        Invocation.getter(#conn),
        returnValue: _FakeConn_7(
          this,
          Invocation.getter(#conn),
        ),
      ) as _i9.Conn);

  @override
  _i8.P2PStream<_i21.Uint8List> get incoming => (super.noSuchMethod(
        Invocation.getter(#incoming),
        returnValue: _FakeP2PStream_6<_i21.Uint8List>(
          this,
          Invocation.getter(#incoming),
        ),
      ) as _i8.P2PStream<_i21.Uint8List>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get isWritable => (super.noSuchMethod(
        Invocation.getter(#isWritable),
        returnValue: false,
      ) as bool);

  @override
  String id() => (super.noSuchMethod(
        Invocation.method(
          #id,
          [],
        ),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.method(
            #id,
            [],
          ),
        ),
      ) as String);

  @override
  String protocol() => (super.noSuchMethod(
        Invocation.method(
          #protocol,
          [],
        ),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.method(
            #protocol,
            [],
          ),
        ),
      ) as String);

  @override
  _i15.Future<void> setProtocol(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setProtocol,
          [id],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i8.StreamStats stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _FakeStreamStats_9(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        ),
      ) as _i8.StreamStats);

  @override
  _i11.StreamManagementScope scope() => (super.noSuchMethod(
        Invocation.method(
          #scope,
          [],
        ),
        returnValue: _FakeStreamManagementScope_10(
          this,
          Invocation.method(
            #scope,
            [],
          ),
        ),
      ) as _i11.StreamManagementScope);

  @override
  _i15.Future<_i21.Uint8List> read([int? maxLength]) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [maxLength],
        ),
        returnValue: _i15.Future<_i21.Uint8List>.value(_i21.Uint8List(0)),
      ) as _i15.Future<_i21.Uint8List>);

  @override
  _i15.Future<void> write(_i21.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> closeWrite() => (super.noSuchMethod(
        Invocation.method(
          #closeWrite,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> closeRead() => (super.noSuchMethod(
        Invocation.method(
          #closeRead,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> setDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setDeadline,
          [time],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> setReadDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setReadDeadline,
          [time],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> setWriteDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setWriteDeadline,
          [time],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);
}

/// A class which mocks [Conn].
///
/// See the documentation for Mockito's code generation for more information.
class MockConn extends _i1.Mock implements _i9.Conn {
  MockConn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i15.Future<List<_i8.P2PStream<dynamic>>> get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _i15.Future<List<_i8.P2PStream<dynamic>>>.value(
            <_i8.P2PStream<dynamic>>[]),
      ) as _i15.Future<List<_i8.P2PStream<dynamic>>>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i2.PeerId get localPeer => (super.noSuchMethod(
        Invocation.getter(#localPeer),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#localPeer),
        ),
      ) as _i2.PeerId);

  @override
  _i2.PeerId get remotePeer => (super.noSuchMethod(
        Invocation.getter(#remotePeer),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#remotePeer),
        ),
      ) as _i2.PeerId);

  @override
  _i15.Future<_i23.PublicKey?> get remotePublicKey => (super.noSuchMethod(
        Invocation.getter(#remotePublicKey),
        returnValue: _i15.Future<_i23.PublicKey?>.value(),
      ) as _i15.Future<_i23.PublicKey?>);

  @override
  _i9.ConnState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeConnState_11(
          this,
          Invocation.getter(#state),
        ),
      ) as _i9.ConnState);

  @override
  _i12.MultiAddr get localMultiaddr => (super.noSuchMethod(
        Invocation.getter(#localMultiaddr),
        returnValue: _FakeMultiAddr_12(
          this,
          Invocation.getter(#localMultiaddr),
        ),
      ) as _i12.MultiAddr);

  @override
  _i12.MultiAddr get remoteMultiaddr => (super.noSuchMethod(
        Invocation.getter(#remoteMultiaddr),
        returnValue: _FakeMultiAddr_12(
          this,
          Invocation.getter(#remoteMultiaddr),
        ),
      ) as _i12.MultiAddr);

  @override
  _i9.ConnStats get stat => (super.noSuchMethod(
        Invocation.getter(#stat),
        returnValue: _FakeConnStats_13(
          this,
          Invocation.getter(#stat),
        ),
      ) as _i9.ConnStats);

  @override
  _i11.ConnScope get scope => (super.noSuchMethod(
        Invocation.getter(#scope),
        returnValue: _FakeConnScope_14(
          this,
          Invocation.getter(#scope),
        ),
      ) as _i11.ConnScope);

  @override
  _i15.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<_i8.P2PStream<dynamic>> newStream(_i16.Context? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [context],
        ),
        returnValue:
            _i15.Future<_i8.P2PStream<dynamic>>.value(_FakeP2PStream_6<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [context],
          ),
        )),
      ) as _i15.Future<_i8.P2PStream<dynamic>>);
}

/// A class which mocks [Peerstore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerstore extends _i1.Mock implements _i3.Peerstore {
  MockPeerstore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AddrBook get addrBook => (super.noSuchMethod(
        Invocation.getter(#addrBook),
        returnValue: _FakeAddrBook_15(
          this,
          Invocation.getter(#addrBook),
        ),
      ) as _i3.AddrBook);

  @override
  _i3.KeyBook get keyBook => (super.noSuchMethod(
        Invocation.getter(#keyBook),
        returnValue: _FakeKeyBook_16(
          this,
          Invocation.getter(#keyBook),
        ),
      ) as _i3.KeyBook);

  @override
  _i3.PeerMetadata get peerMetadata => (super.noSuchMethod(
        Invocation.getter(#peerMetadata),
        returnValue: _FakePeerMetadata_17(
          this,
          Invocation.getter(#peerMetadata),
        ),
      ) as _i3.PeerMetadata);

  @override
  _i3.Metrics get metrics => (super.noSuchMethod(
        Invocation.getter(#metrics),
        returnValue: _FakeMetrics_18(
          this,
          Invocation.getter(#metrics),
        ),
      ) as _i3.Metrics);

  @override
  _i3.ProtoBook get protoBook => (super.noSuchMethod(
        Invocation.getter(#protoBook),
        returnValue: _FakeProtoBook_19(
          this,
          Invocation.getter(#protoBook),
        ),
      ) as _i3.ProtoBook);

  @override
  _i15.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<_i13.AddrInfo> peerInfo(_i2.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #peerInfo,
          [id],
        ),
        returnValue: _i15.Future<_i13.AddrInfo>.value(_FakeAddrInfo_20(
          this,
          Invocation.method(
            #peerInfo,
            [id],
          ),
        )),
      ) as _i15.Future<_i13.AddrInfo>);

  @override
  _i15.Future<List<_i2.PeerId>> peers() => (super.noSuchMethod(
        Invocation.method(
          #peers,
          [],
        ),
        returnValue: _i15.Future<List<_i2.PeerId>>.value(<_i2.PeerId>[]),
      ) as _i15.Future<List<_i2.PeerId>>);

  @override
  _i15.Future<void> removePeer(_i2.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #removePeer,
          [id],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<void> addOrUpdatePeer(
    _i2.PeerId? peerId, {
    List<_i12.MultiAddr>? addrs,
    List<String>? protocols,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdatePeer,
          [peerId],
          {
            #addrs: addrs,
            #protocols: protocols,
            #metadata: metadata,
          },
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  _i15.Future<_i24.PeerInfo?> getPeer(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeer,
          [peerId],
        ),
        returnValue: _i15.Future<_i24.PeerInfo?>.value(),
      ) as _i15.Future<_i24.PeerInfo?>);
}
